### ISSUE TITLE
error while loading mod 1.16.4

### ISSUE THREAD

**Issue by EgorimM** [Sinhika/SimpleOres2#45]
Hello, I'm getting an error while using your mod.
Error in item ID and name.
What should I do?

Mod version 1.16.4 2.4.2.3
Forge 35.1.0

Log

Error loading mods
error has occurred during loading
Simple Ores (simpleores) encountered an error during the load_registries event phase javalang. Illegal5tateException: Attempted to set registry name with existing registry name! Neu: silents_nechanisms: crushing

all log

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 03.12.20 9:32
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5561/883565082.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5336/2127082439.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.0.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/81355344.call(Unknown Source) [forge-1.16.4-35.1.0.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:43) ~[?:?] {re:classloading,re:mixin}
-- MOD simpleores --
Details:
	Mod File: мод на руды SimpleOres2-1.16.4-2.4.2.3.jar
	Failure message: Simple Ores (simpleores) encountered an error during the load_registries event phase
		java.lang.IllegalStateException: Attempted to set registry name with existing registry name! New: silents_mechanisms:crushing Old: silents_mechanisms:crushing
	Mod Version: 1.16.4-2.4.2.3
	Mod Issue URL: https://github.com/Sinhika/SimpleOres2/issues
	Exception message: java.lang.IllegalStateException: Attempted to set registry name with existing registry name! New: silents_mechanisms:crushing Old: silents_mechanisms:crushing
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:43) ~[?:?] {re:classloading,re:mixin}
	at mod.alexndr.simpleores.ModEventSubscriber.onRegisterRecipeSerializers(ModEventSubscriber.java:96) ~[?:1.16.4-2.4.2.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_144_ModEventSubscriber_onRegisterRecipeSerializers_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3100/241316255.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2894/621209929.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2895/1864122136.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.0.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/81355344.call(Unknown Source) [forge-1.16.4-35.1.0.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2789867232 bytes (2660 MB) / 4261412864 bytes (4064 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/оптифайн%20OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.0
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |COMMON_SET|NOSIGNATURE
		мод на руды дополненеие Netherrocks-1.16.4-2.3.2.0|SimpleOres:Netherrocks        |netherrocks                   |1.16.4-2.3.2.0      |COMMON_SET|NOSIGNATURE
		сам мод--morevanillalib-1.16.4-1.3.8 но это библио|MoreVanillaLib                |morevanillalib                |1.3.8               |COMMON_SET|NOSIGNATURE
		мод на декор  variant16x-1.16.4-v0.17.4_beta_pre3.|Variant16x                    |variant16x                    |0.17.4_beta_pre3    |COMMON_SET|NOSIGNATURE
		мод на лопаты vanillaexcavators-1.16.4-2.2.0.jar  |Vanilla Excavators            |vanillaexcavators             |2.2.0               |COMMON_SET|NOSIGNATURE
		мод на исправление молока nutritiousmilk-1.16.4_1.|Nutritious Milk               |nutritiousmilk                |1.2                 |COMMON_SET|NOSIGNATURE
		сам мод--SimpleCoreLib-1.16.4-2.0.3.2 но это библи|SimpleCoreLib                 |simplecorelib                 |1.16.4-2.0.3.2      |COMMON_SET|NOSIGNATURE
		мод на руды в аду Janoeo-4.5.0.63-experimental.jar|Janoeo                        |janoeo                        |4.5.0.63-experimenta|COMMON_SET|NOSIGNATURE
		мод на подсказки jei-1.16.4-7.6.0.58.jar          |Just Enough Items             |jei                           |7.6.0.58            |COMMON_SET|NOSIGNATURE
		мод на инструменты morevanillatools-1.16.4-2.1.5.j|MoreVanillaTools              |morevanillatools              |2.1.5               |COMMON_SET|NOSIGNATURE
		мод на супер бочки metalbarrels-3.3a.jar          |Metal Barrels                 |metalbarrels                  |3.3a                |COMMON_SET|NOSIGNATURE
		мод на новые банеры AdditionalBanners-1.16.4-5.0.3|AdditionalBanners             |additionalbanners             |5.0.3               |COMMON_SET|ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		мод на растения simplefarming-1.16.4-1.3.5.jar    |Simple Farming                |simplefarming                 |1.16.4-1.3.5        |COMMON_SET|NOSIGNATURE
		домак индикатор torohealth-1.16.4-forge-2.jar     |ToroHealth                    |torohealth                    |NONE                |COMMON_SET|NOSIGNATURE
		сам мод--curios-forge-1.16.4-4.0.3.0 но это библио|Curios API                    |curios                        |1.16.4-4.0.3.0      |COMMON_SET|NOSIGNATURE
		мод на кольца RingsOfAscension-1.16.4-1.6.0.jar   |Rings of Ascension            |ringsofascension              |1.6.0               |COMMON_SET|NOSIGNATURE
		сам мод--diabololib-1.0.4 но это библиотека к моду|Diabolo Lib                   |diolib                        |1.0.4               |COMMON_SET|NOSIGNATURE
		сам мод--collective_1.16.4_1.53 но это библиотека |Collective                    |collective                    |1.53                |COMMON_SET|NOSIGNATURE
		мод не переплавку гнилой плоти jrftl1.16.4-1.1.jar|JRFTL                         |jrftl                         |1.1                 |COMMON_SET|NOSIGNATURE
		мод на предотвращение ошибок при загрузке мира shu|Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |COMMON_SET|NOSIGNATURE
		мод на фейковые блоки fakeblocks-1.16.4-1.0.1.jar |Fake Blocks                   |fakeblocks                    |1.16.4-1.0.1        |COMMON_SET|NOSIGNATURE
		мод на крафты разъединить polymorph-forge-1.16.4-0|Polymorph                     |polymorph                     |1.16.4-0.18         |COMMON_SET|NOSIGNATURE
		мод на всё из бетона sweetconcrete-1.16.4-1.7.1.ja|Sweet Concrete                |sweetconcrete                 |1.16.3-1.7.1        |COMMON_SET|NOSIGNATURE
		мод на фруктовые деревья FruitTrees-1.16.3-2.2.0.j|Fruit Trees                   |fruittrees                    |2.2.0               |COMMON_SET|NOSIGNATURE
		сам мод--Kiwi-1.16.3-3.4.1 но это библиотека к мод|Kiwi                          |kiwi                          |3.4.1               |COMMON_SET|NOSIGNATURE
		мод на мобов из маинкрафт земли earthmobsmod-1.16.|Earth Mobs Mod                |earthmobsmod                  |1.16.4-0.1.2-Beta   |COMMON_SET|NOSIGNATURE
		мод на руды в аду BasicNetherOres-1.16.4-5.4.0.jar|Basic Nether Ores             |bno                           |5.4.0               |COMMON_SET|NOSIGNATURE
		мод на молоты vanillahammers-1.16.4-2.2.0.jar     |Vanilla Hammers               |vanillahammers                |2.2.0               |COMMON_SET|NOSIGNATURE
		мод на золотую ягоду Golden-Berry-Mod-1.16.4-1.0.0|Golden Berry Mod              |goldenberry                   |1.0.0               |COMMON_SET|NOSIGNATURE
		сам мод--Bookshelf-1.16.4-9.2.14 но это библиотека|Bookshelf                     |bookshelf                     |9.2.14              |COMMON_SET|ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		мод на отображение топора WorldEdit-CUI-FE3-1.16.4|WorldEdit CUI Forge Edition 3 |worldeditcuife3               |3.0.8               |COMMON_SET|NOSIGNATURE
		сам мод--u_team_core-1.16.4-3.1.13.187 но это библ|U Team Core                   |uteamcore                     |3.1.13.187          |COMMON_SET|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		мод на топор worldedit-forge-mc1.16.3-7.2.0-dist.j|WorldEdit                     |worldedit                     |7.2.0+a51fa43       |COMMON_SET|NOSIGNATURE
		мод на броню morevanillaarmor-1.16.4-1.2.jar      |MoreVanillaArmor              |morevanillaarmor              |1.16.2-1.2          |COMMON_SET|NOSIGNATURE
		мод на шалкеры ironshulkerboxes-1.16.4-5.1.9.jar  |Iron Shulker Boxes            |ironshulkerbox                |1.16.4-5.1.9        |COMMON_SET|NOSIGNATURE
		мод на биомы Oh The Biomes You'll Go byg-1.1.5.jar|Oh The Biomes You'll Go       |byg                           |1.1.5               |COMMON_SET|NOSIGNATURE
		мини карта forgemod_VoxelMap-1.10.14_for_1.16.4.ja|VoxelMap                      |voxelmap                      |1.10.14             |COMMON_SET|NOSIGNATURE
		мод на беттер фпс пвп фери плей BetterPvP_20.28.1_|Better PVP Mod                |xaerobetterpvp                |20.28.1             |COMMON_SET|NOSIGNATURE
		forge-1.16.4-35.1.0-universal.jar                 |Forge                         |forge                         |35.1.0              |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		мод на показ сытости AppleSkin-mc1.16.2-forge-1.0.|AppleSkin                     |appleskin                     |1.0.14              |COMMON_SET|NOSIGNATURE
		мод на декор absentbydesign-1.16.3-1.1.1.jar      |Absent By Design Mod          |absentbydesign                |1.16.3-1.1.1        |COMMON_SET|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		мод на инструменты PattysMoreStuff-Stable-1.16.4-1|pattysmorestuff               |pattysmorestuff               |1.3.0               |COMMON_SET|NOSIGNATURE
		мод на шахты BetterMineshafts-Forge-1.16.3-1.1.jar|YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1          |COMMON_SET|NOSIGNATURE
		мод на руды SimpleOres2-1.16.4-2.4.2.3.jar        |Simple Ores                   |simpleores                    |1.16.4-2.4.2.3      |VALIDATE  |NOSIGNATURE
		мод на топоры lumberjack-2.1.4.jar                |LumberJack                    |lumberjack                    |2.1.4               |COMMON_SET|NOSIGNATURE
		мод на сундуки ironchest-1.16.4-11.2.10.jar       |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |COMMON_SET|NOSIGNATURE
		мод на свои крафты CraftingTweaks_1.16.3-12.2.0.ja|Crafting Tweaks               |craftingtweaks                |12.2.0              |COMMON_SET|NOSIGNATURE
		мод на редактирование нбт тегов IBEEditor-1.16.4-1|IBE Editor                    |ibeeditor                     |1.2.0               |COMMON_SET|NOSIGNATURE
	Crash Report UUID: 25972174-b4c9-44eb-bdd7-0c65f10fa5b8
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:core
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 430/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Sinhika** [comment]
I still can't duplicate this bug, but I have attempted a "brute-force" fix to the problem. (Commit 98bc702a1b410f18fe5dbd24b9a1ed9fc19f5380)

Try the latest version (1.16.4-2.4.2.4 or later). Also update to the latest version of Netherrocks if you are using that.
